### ISSUE TITLE
Description of A, I = p.PL(2, 2, 1.95)?

### ISSUE THREAD

**Issue by Arindamsannyal** [sheriftawfikabbas/pyphotonics#1]
Dear Altruists

Thank you very much for developing such a nice tool to calculate photoluminescence (PL). Sir, I am trying to calculate the PL spectrum of GaN and followed each ground state, excited state, and vibrational calculation. Then, when I ran the python code to calculate the PL-spectrum, I found no peak in the generated 'I.png' file. I modified the values in the A, I = p.PL(2, 2, 1.95) line arbitrarily but could not understand the proper meaning of these values in the () bracket.

Can you please help me with this issue of setting proper values in the () bracket? Thank you very much for your kind consideration.

Best regards
Arindam Sannyal

**Comment by sheriftawfikabbas** [comment]
H Arindam,

Apologies for the delay.

According to the definition of that function PL(self, gamma, SHR, EZPL):

EZPL is the E_ZPL value that you wish to use to centre the peak of the ZPL Lorentzian in your line-shape, gamma and SHR are both fitting parameters; gamma is in Eq. 16 of the manuscript (the line width), and SHR is mentioned in Ref. 13 in the definition of G(t). Given that the position and shape of the Lorentzian are not derived from ab initio theory, these values are there to fit it to your measured spectrum.

You should at least see a peak at 1.95 eV (the third argument to the method). Happy to check your data file to see what's happening.

Sherif

**Comment by sheriftawfikabbas** [comment]
Issue closed
