### ISSUE TITLE
Auger carrier lifetime

### ISSUE THREAD

**Issue by Arindamsannyal** [sheriftawfikabbas/pyphotonics#2]
Dear Sir

Thank you very much for developing such a nice code for photonic properties. Sir, I would like to know that is it possible to calculate Auger carrier lifetime by PyPhotonics as it is mentioned that soon PyPhotonics will be able to calculate the carrier lifetimes for defects.

Thank you very much for your time.

Best regards
Arindam Sannyal

**Comment by sheriftawfikabbas** [comment]
You will be notified once it's implemented.

**Comment by Arindamsannyal** [comment]
Dear Sir

Thank you for your response.

Best Regards
Arindam Sannyal
