### ISSUE TITLE
Value of h_bar?

### ISSUE THREAD

**Issue by Shibu778** [sheriftawfikabbas/pyphotonics#5]
https://github.com/sheriftawfikabbas/pyphotonics/blob/720584f6505fa7d07411b591bc3906e71b28a987/pyphotonics/photoluminescence.py#L198C50-L198C50

I want to know why you have multiplied (1.0545718e-34 * 6.582119514e-16) in the above line. However, both represent h_bar in different units.

Reduced Plank Constant = 1.054571817...×10−34 J⋅s (=6.582119569...×10−16 eV⋅s)

**Comment by haiyuanwang2020** [comment]
Hi, I have the same question. Do you have the answer now?

**Comment by haiyuanwang2020** [comment]
I have the same question. Do you have the answer now, @Shibu778 ?

**Comment by Shibu778** [comment]
Okay. Now I got the answer. The first $\hbar$ `1.0545718e-34` (in unit of J.s)  for dividing $\hbar$ in the following equation. The second $\hbar$ of `6.582119514e-16` (in unit of eV.s) converts the $\omega_k$ (in unit of eV) to `Hz` or $\frac{1}{s}$.

$$
S_k = \frac{\omega_k * q_k^2}{2\hbar}
$$
